<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gb</string>
	</array>
	<key>name</key>
	<string>Grobots</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>comments</string>
			<key>match</key>
			<string>;+.*?$</string>
			<key>name</key>
			<string>comment.line.grobots</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.grobots</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.grobots</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.other.grobots</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>markup</string>
			<key>match</key>
			<string>^(#)(side|author|decoration|color|date|type|end)(.*?)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.grobots</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.grobots</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.grobots</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>seed markup</string>
			<key>match</key>
			<string>^(#)(seed)((?:\s+(?:(?:\d+\.?\d*)|(?:\.\d+)))+)\s*(?:;+.*)?$</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(#)(hardware)\s*(?:;+.*)?$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.grobots</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.grobots</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>hardware</string>
			<key>end</key>
			<string>^(?=#)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.grobots</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.grobots</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>single-param hardware defs</string>
					<key>match</key>
					<string>^(engine|constructor|solar-cells|eater|armor|repair-rate|shield|bomb)\s+((\d+\.?\d*)|(\.\d+))\s*?(?:;+.*)?$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.grobots</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.grobots</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.grobots</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>2-param hardware defs</string>
					<key>match</key>
					<string>^(energy|force-field)\s+((\d+\.?\d*)|(\.\d+))\s+((\d+\.?\d*)|(\.\d+))\s*?(?:;+.*)?$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.grobots</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.grobots</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.grobots</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>2-param one optional hardware defs</string>
					<key>match</key>
					<string>^(processor|syphon|enemy-syphon|robot-sensor|food-sensor|shot-sensor)\s+((\d+\.?\d*)|(\.\d+))(\s+((\d+\.?\d*)|(\.\d+)))?\s*?(?:;+.*)?$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.grobots</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.grobots</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.grobots</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.grobots</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>3-param hardware defs</string>
					<key>match</key>
					<string>^(blaster|grenades)\s+((\d+\.?\d*)|(\.\d+))\s+((\d+\.?\d*)|(\.\d+))\s+((\d+\.?\d*)|(\.\d+))\s*?(?:;+.*)?$</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(#)(code)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.grobots</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.grobots</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>code</string>
			<key>end</key>
			<string>^(?=#(hardware|type))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.grobots</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>If-else-then</string>
					<key>match</key>
					<string>(?&lt;=^|\s)((?:n?if)|and-if|(?:c?else)|then)(?=\s)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.grobots</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>do-While-loop</string>
					<key>match</key>
					<string>\b(do|(?:while-|until-)?loop|while|util|forever)\s</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.grobots</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>other control statements</string>
					<key>match</key>
					<string>\b(return|jump|call|ifg|nifg|ifeg|ifc|ifec|nifc|ifr|nifr)\s</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.grobots</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>labels and returns</string>
					<key>match</key>
					<string>(:|&amp;|^)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.grobots</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.grobots</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.grobots</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.grobots</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>consts</string>
					<key>match</key>
					<string>^(#)(const)\s+([\w-]+)\s+((\d+\.?\d*)|(\.\d+))\s*(?:;+.*)?$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.grobots</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.grobots</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.grobots</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.grobots</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>vars</string>
					<key>match</key>
					<string>^(#)(var)\s+([\w-]+)(?:\s+((\d+\.?\d*)|(\.\d+)))?\s*(?:;+.*)?$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.grobots</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.grobots</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.grobots</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.grobots</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.grobots</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>vects</string>
					<key>match</key>
					<string>^(#)(vector)\s+([\w-]+)(?:\s+((?:\d+\.?\d*)|(?:\.\d+))\s+((?:\d+\.?\d*)|(?:\.\d+)))?\s*(?:;+.*)?$</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>hardware keyword Variables, basics and constructor</string>
					<key>match</key>
					<string>(?&lt;=^|\s)(time|world-(?:size|width|height)|position|velocity|radius|mass|speed|side|type|id|parent-id|processor|remaining|engine-(?:power|max-power|velocity)|(?:friendly-|enemy-|food-|shot-|wall-)?collision|flag|energy|max-energy|solar-cells|eater|eaten|syphon(?:-max-rate|-range|-distance|-direction|-rate|ed)|constructor-(?:max-rate|rate|type|progress|remaining)|child-id)(?=^|\s|!)</string>
					<key>name</key>
					<string>variable.language.grobots</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>hardware keyword variables sensors generic</string>
					<key>match</key>
					<string>(?&lt;=^|\s)((robot|food|shot)-(?:sensor-(?:range|firing-cost|time|focus-(?:distance|direction))|found|position(?:-overall)?|velocity|distance(?:-overall)?|direction(?:-overall)?|side|radius))</string>
					<key>name</key>
					<string>variable.language.grobots</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.language.grobots</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>variable sensors; specific</string>
					<key>match</key>
					<string>(?&lt;=^|\s)((?:(?:robot|shot)-type)|(?:robot-(?:id|shield-fraction|bomb|reloading|sensor-sees-(?:friends|enemies)))|(?:(?:robot|food)-(?:mass|energy))|(?:shot-(?:power|sensor-sees-(?:enemy|friendly))))(?=^|\s|!)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.language.grobots</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>variables defenses</string>
					<key>match</key>
					<string>(?&lt;=^|\s)((?:max-)?(?:armor|repair-rate|shield)|shield-fraction|last-hit)(?=^|\s|!)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.language.grobots</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>variables offenses; blaster+grenades</string>
					<key>match</key>
					<string>(?&lt;=^|\s)((?:blaster|grenades)-(?:damage|range|speed|lifetime|reload-time|firing-cost|cooldown)|grenades-radius)(?=^|\s|!)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.language.grobots</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>variables offenses; forcefield+syphon</string>
					<key>match</key>
					<string>(?&lt;=^|\s)((?:force-field-|enemy-syphon-)(range|distance|direction)|force-field-(?:(?:max-)?power|angle|radius)|enemy-syphon(?:(?:-max)?-rate|ed))(?=^|\s|!)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.grobots</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>operators basics, constructor</string>
					<key>match</key>
					<string>(?&lt;=^|\s)(seek-(?:moving-)?location|restrict-position|die|v?(?:write|read)|(?:clear-|skip-)?messages|send|receive|type-population|autoconstruct|balance-type)(?=^|\s|!)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.grobots</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>operators sensors, offenses</string>
					<key>match</key>
					<string>(?&lt;=^|\s)((?:fire|periodic)-(?:robot|food|shot)-sensor|next-(?:robot|food|shot)|(?:fire|lead)-(?:blaster|grenade)|set-force-field)(?=^|\s)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>base language variables</string>
					<key>match</key>
					<string>(?&lt;=^|\s)(stack(?:-limit)?)(?=^|\s)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.function</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>stack operators</string>
					<key>match</key>
					<string>(?&lt;=^|\s)((?:n|dr|2dr|rdr)op|nip|dropn|2?swap|r?rot|2?dup|tuck|2?over|pick|&gt;r|r&gt;)(?=^|\s)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.function</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>arithmetic</string>
					<key>match</key>
					<string>(?&lt;=^|\s)(\+|-|\*|/|negate|reciprocal|mod|rem|square|sqrt|exponent|floor|ceiling|round|min|max|abs|signum|reorient|(?:arc)?(?:sin|cos|tan)|arctan2|random(?:-angle|-int|-bool)?|pi|2pi|pi/2|e|epsilon|infinity|rect-to-polar|polar-to-rect|v(?:\+|-|negate|s\*|s/)|norm|angle|dot|project|cross|unitize|dist|in-range)(?=^|\s)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.function</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>boolean and misc operators</string>
					<key>match</key>
					<string>(?&lt;=^|\s)(=|&lt;&gt;|&lt;|&gt;|&lt;=|&gt;=|not|n?and|(?:n|x)?or|ifev|v?print|beep|pause|stop|sync|v?store|v?load)(?=^|\s)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.function</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>suffixes</string>
					<key>match</key>
					<string>(?&lt;=\w)(!|&amp;|\^|:)(?=^|\s)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.grobots</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>numerical constants</string>
					<key>match</key>
					<string>(?&lt;=^|\s)((\d+\.?\d*)|(\.\d+))(?=^|\s)</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.grobots</string>
	<key>uuid</key>
	<string>7490e7e4-b4a8-4524-bbae-e71cc974cf47</string>
</dict>
</plist>
